[build]
    functions = "functions/"
    publish = "dist/"

[[redirects]]
    from = "/cuaca"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/basis-data"
    to = "/"
    status = 200